default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  host: localhost
  username: postgres
  password: 1985

development:
  <<: *default
  database: yacht_app_development
  

test:
  <<: *default
  database: yacht_app_test

production:
  <<: *default
  database: yacht_app_production